package andreasWallner.xilinx

import spinal.core._
import spinal.lib._
import spinal.lib.bus.amba4.axilite.{
  AxiLite4,
  AxiLite4Ax,
  AxiLite4B,
  AxiLite4Config,
  AxiLite4R,
  AxiLite4W
}
import spinal.lib.bus.amba4.axi.{Axi4, Axi4Ax, Axi4B, Axi4Config, Axi4R, Axi4W}
import spinal.lib.IMasterSlave
import spinal.lib.bus.amba3.apb.Apb3

import scala.collection.mutable.Map

object XilinxSupportFactory {
  def makeSupport(bundle: IMasterSlave): Option[BusSupport] =
    bundle match {
      case axilite: AxiLite4 => Some(AxiLite4Support(axilite))
      case axi: Axi4         => Some(Axi4Support(axi))
      case apb: Apb3         => Some(Apb3Support(apb))
      case _                 => None
    }
}

trait BusSupport {
  def name(idx: Integer): String

  def rename(idx: Integer): Unit

  def addAttributes(idx: Integer): Unit

  def portMaps(): List[PortMap]

  def busType: SpiritBusType

  def abstractionType: SpiritAbstractionType
}

/**
  * Rename Axi4-Lite bus as expected by Xilinx Vivado toolset
  *
  * Names are in accordance with what is autogenerated by Vivado.
  */
case class AxiLite4Support(axilite: AxiLite4) extends BusSupport {
  def name(idx: Integer): String = {
    val dirPrefix = if (axilite.isMasterInterface) "M" else "S"
    val idxPrefix = f"$idx%02d"
    dirPrefix + idxPrefix + "_AXI"
  }

  def rename(idx: Integer): Unit = {
    val prefix = name(idx) + "_"

    renameAx(axilite.aw, prefix, "w")
    renameW(axilite.w, prefix)
    renameB(axilite.b, prefix)
    renameAx(axilite.ar, prefix, "r")
    renameR(axilite.r, prefix)
  }

  def renameAx(ax: Stream[AxiLite4Ax], prefix: String, rw: String): Unit = {
    ax.addr.setName(prefix + f"a${rw}addr")
    ax.prot.setName(prefix + f"a${rw}prot")
    ax.valid.setName(prefix + f"a${rw}valid")
    ax.ready.setName(prefix + f"a${rw}ready")
  }

  def renameW(w: Stream[AxiLite4W], prefix: String): Unit = {
    w.data.setName(prefix + f"wdata")
    w.strb.setName(prefix + f"wstrb")
    w.valid.setName(prefix + f"wvalid")
    w.ready.setName(prefix + f"wready")
  }

  def renameB(b: Stream[AxiLite4B], prefix: String): Unit = {
    b.resp.setName(prefix + f"bresp")
    b.valid.setName(prefix + f"bvalid")
    b.ready.setName(prefix + f"bready")
  }

  def renameR(r: Stream[AxiLite4R], prefix: String): Unit = {
    r.data.setName(prefix + f"rdata")
    r.resp.setName(prefix + f"rresp")
    r.valid.setName(prefix + f"rvalid")
    r.ready.setName(prefix + f"rready")
  }

  def portMaps(): List[PortMap] = {
    import axilite._
    List(
      PortMap("AWADDR", aw.addr),
      PortMap("AWPROT", aw.prot),
      PortMap("AWVALID", aw.valid),
      PortMap("AWREADY", aw.ready),
      PortMap("WDATA", w.data),
      PortMap("WSTRB", w.strb),
      PortMap("WVALID", w.valid),
      PortMap("WREADY", w.ready),
      PortMap("BRESP", b.resp),
      PortMap("BVALID", b.valid),
      PortMap("BREADY", b.ready),
      PortMap("ARADDR", ar.addr),
      PortMap("ARPROT", ar.prot),
      PortMap("ARVALID", ar.valid),
      PortMap("ARREADY", ar.ready),
      PortMap("RDATA", r.data),
      PortMap("RRESP", r.resp),
      PortMap("RVALID", r.valid),
      PortMap("RREADY", r.ready)
    )
  }

  def busType: SpiritBusType =
    SpiritBusType("xilinx.com", "interface", "aximm", "1.0")

  def abstractionType: SpiritAbstractionType =
    SpiritAbstractionType("xilinx.com", "interface", "aximm_rtl", "1.0")

  override def addAttributes(idx: Integer): Unit = ???
}

case class Apb3Support(apb3: Apb3) extends BusSupport {
  def dirPrefix = if (apb3.isMasterInterface) "M" else "S"

  def name(idx: Integer): String = {
    val idxPrefix = f"$idx%02d_APB"
    dirPrefix + idxPrefix + "_"
  }

  def rename(idx: Integer): Unit = {
    val prefix = name(idx)

    apb3.PADDR.setName(prefix + "PADDR")
    apb3.PENABLE.setName(prefix + "PENABLE")
    apb3.PRDATA.setName(prefix + "PRDATA")
    apb3.PREADY.setName(prefix + "PREADY")
    apb3.PSEL.setName(prefix + "PSEL")
    apb3.PSLVERROR.setName(prefix + "PSLVERR")
    apb3.PWDATA.setName(prefix + "PWDATA")
    apb3.PWRITE.setName(prefix + "PWRITE")
  }

  def addAttributes(idx: Integer): Unit = {
    def name = f"APB_${dirPrefix}${idx}"
    def attr = "X_INTERFACE_INFO"
    def info = "xilinx.com:interface:apb:1.0 " + name + " "
    for (mapping <- portMaps())
      mapping.physicalPort.addAttribute(attr, info + mapping.logicalPort)
  }

  override def portMaps() = List(
    PortMap("PADDR", apb3.PADDR),
    PortMap("PENABLE", apb3.PENABLE),
    PortMap("PRDATA", apb3.PRDATA),
    PortMap("PREADY", apb3.PREADY),
    PortMap("PSEL", apb3.PSEL),
    PortMap("PSLVERR", apb3.PSLVERROR),
    PortMap("PWDATA", apb3.PWDATA),
    PortMap("PWRITE", apb3.PWRITE)
  )

  override def busType = SpiritBusType("xilinx.com", "interface", "apb", "1.0")

  override def abstractionType =
    SpiritAbstractionType("xilinx.com", "interface", "apb_rtl", "1.0")
}

case class Axi4Support(axi4: Axi4) extends BusSupport {
  def name(idx: Integer): String = {
    val dirPrefix = if (axi4.isMasterInterface) "M" else "S"
    val idxPrefix = f"$idx%02d"
    dirPrefix + idxPrefix + "_"
  }

  def rename(idx: Integer): Unit = {
    val prefix = name(idx)

    renameAx(axi4.aw, prefix, "w", axi4.config, axi4.config.awUserWidth)
    renameW(axi4.w, prefix, axi4.config)
    renameB(axi4.b, prefix, axi4.config)
    renameAx(axi4.ar, prefix, "r", axi4.config, axi4.config.arUserWidth)
    renameR(axi4.r, prefix, axi4.config)
  }

  def renameAx[T <: Axi4Ax](
      ax: Stream[T],
      prefix: String,
      rw: String,
      config: Axi4Config,
      userWidth: Int
  ): Unit = {
    import config._
    ax.addr.setName(prefix + f"A${rw}ADDR")
    if (useId) ax.id.setName(prefix + f"A${rw}ID")
    if (useRegion) ax.region.setName(prefix + f"A${rw}REGION")
    if (useLen) ax.len.setName(prefix + f"A${rw}LEN")
    if (useSize) ax.size.setName(prefix + f"A${rw}SIZE")
    if (useBurst) ax.burst.setName(prefix + f"A${rw}BURST")
    if (useLock) ax.lock.setName(prefix + f"A${rw}LOCK")
    if (useCache) ax.cache.setName(prefix + f"A${rw}CACHE")
    if (useQos) ax.qos.setName(prefix + f"A${rw}QOS")
    if (userWidth >= 0) ax.user.setName(prefix + f"A${rw}USER")
    if (useProt) ax.prot.setName(prefix + f"A${rw}PROT")
    ax.valid.setName(prefix + f"A${rw}VALID")
    ax.ready.setName(prefix + f"A${rw}READY")
  }

  def renameW(w: Stream[Axi4W], prefix: String, config: Axi4Config): Unit = {
    import config._
    w.data.setName(prefix + f"WDATA")
    if (useStrb) w.strb.setName(prefix + f"WSTRB")
    if (wUserWidth >= 0) w.user.setName(prefix + f"WUSER")
    if (useLast) w.last.setName(prefix + f"WLAST")
    w.valid.setName(prefix + f"WVALID")
    w.ready.setName(prefix + f"WREADY")
  }

  def renameB(b: Stream[Axi4B], prefix: String, config: Axi4Config): Unit = {
    import config._
    if (useId) b.id.setName(prefix + f"BID")
    if (useResp) b.resp.setName(prefix + f"BRESP")
    if (bUserWidth >= 0) b.user.setName(prefix + f"BUSER")
    b.valid.setName(prefix + f"BVALID")
    b.ready.setName(prefix + f"BREADY")
  }

  def renameR(r: Stream[Axi4R], prefix: String, config: Axi4Config): Unit = {
    import config._
    r.data.setName(prefix + f"RDATA")
    if (useId) r.id.setName(prefix + f"RID")
    if (useResp) r.resp.setName(prefix + f"RRESP")
    if (useLast) r.last.setName(prefix + f"RLAST")
    if (rUserWidth >= 0) r.user.setName(prefix + f"RUSER")
    r.valid.setName(prefix + f"RVALID")
    r.ready.setName(prefix + f"RREADY")
  }

  def portMaps(): List[PortMap] = {
    List() // TODO
  }

  // TODO check both
  override def busType: SpiritBusType =
    SpiritBusType("xilinx.com", "interface", "aximm", "1.0")

  override def abstractionType: SpiritAbstractionType =
    SpiritAbstractionType("xilinx.com", "interface", "aximm_rtl", "1.0")

  override def addAttributes(idx: Integer): Unit = ???
}

object forMasterSlaveInterfaces {
  var slaveIdx = 0
  var masterIdx = 0

  def apply(that: Component)(f: (IMasterSlave, Int) => Boolean): Unit =
    traverse(that)(f)

  def traverse(that: Component)(f: (IMasterSlave, Int) => Boolean): Unit =
    that.getGroupedIO(true) foreach (process(_)(f))

  def traverse(b: Bundle)(f: (IMasterSlave, Int) => Boolean): Unit =
    b.elements foreach { case (_, d) => process(d)(f) }

  def process(d: Data)(f: (IMasterSlave, Int) => Boolean): Unit = {
    d match {
      case ms: IMasterSlave =>
        val idx = if (ms.isMasterInterface) masterIdx else slaveIdx
        val done = f(ms, idx)

        if (done) {
          if (ms.isMasterInterface) masterIdx else slaveIdx = idx + 1
          return
        }
      case _ =>
    }
    d match {
      case b: Bundle => traverse(b)(f)
      case _         =>
    }
  }
}

object XilinxNamer {
  def apply[T <: Component](comp: T): T = {
    def doIt: Unit = {
      val ios = comp.getGroupedIO(true)

      name_clockDomain(comp.clockDomain)
      add_clockDomain_attributes(comp.clockDomain)

      forMasterSlaveInterfaces(comp) { (intf: IMasterSlave, idx: Int) =>
        XilinxSupportFactory.makeSupport(intf) match {
          case Some(support) =>
            support.rename(idx); support.addAttributes(idx); true
          case _ => false
        }
      }
    }

    comp.addPrePopTask(() => {
      doIt
    })
    comp
  }

  def name_clockDomain(cd: ClockDomain): Unit = {
    cd.clock.setName(
      "ACLK"
        + (cd.frequency match {
          case f: FixedFrequency =>
            Helper.engineeringNotation(f.getValue.toBigDecimal, "Hz")
          case _ => ""
        })
    )
    if (cd.hasResetSignal) {
      cd.reset.setName(
        (if (cd.config.resetKind == ASYNC) "A" else "")
          + "RESET"
          + (if (cd.config.resetActiveLevel == HIGH) "" else "N")
      )
    }

    if (cd.hasClockEnableSignal) {
      cd.clockEnable.setName(
        "CE" + (if (cd.config.resetActiveLevel == HIGH) "" else "N")
      )
    }
  }

  def add_clockDomain_attributes(cd: ClockDomain) = {
    cd.clock.addAttribute(
      "X_INTERFACE_INFO",
      s"xilinx.com:signal:clock:1.0 ${cd.clock.getName()} CLK"
    )
    val clk_param =
      (if (cd.hasResetSignal) s"ASSOCIATED_RESET ${cd.reset.getName()}"
       else
         "") + (cd.frequency match {
        case f: FixedFrequency => s"FREQ_HZ ${f.getValue.toBigDecimal}"
        case _                 => ""
      })
    cd.clock.addAttribute("X_INTERFACE_PARAMETER", clk_param)

    if (cd.hasResetSignal) {
      cd.reset.addAttribute(
        "X_INTERFACE_INFO",
        s"xilinx.com:signal:reset:1.0 ${cd.reset.getName()} RST"
      )
      cd.reset.addAttribute(
        "X_INTERFACE_PARAM",
        "POLARITY " + (if (cd.config.resetActiveLevel == HIGH) "ACTIVE_HIGH"
                       else "ACTIVE_LOW")
      )
    }
    if (cd.hasClockEnableSignal) {
      cd.clockEnable.addAttribute(
        "X_INTERFACE_INFO",
        s"xilinx.com:signal:clockenable:1.0 ${cd.clockEnable.getName()} CE"
      )
      cd.clockEnable
        .addAttribute(
          "X_INTERFACE_PARAMETER",
          "POLARITY " + (if (cd.config.clockEnableActiveLevel == HIGH)
                           "ACTIVE_HIGH"
                         else "ACTIVE_LOW")
        )
    }
  }
}

object Helper {
  def engineeringNotation(
      d: BigDecimal,
      unit: String,
      decimalDigits: Int = 3
  ): String = {
    Seq(
      ("Y", BigDecimal("1000000000000000000000000")),
      ("Z", BigDecimal("1000000000000000000000")),
      ("E", BigDecimal("1000000000000000000")),
      ("P", BigDecimal("1000000000000000")),
      ("T", BigDecimal("1000000000000")),
      ("G", BigDecimal("1000000000")),
      ("M", BigDecimal("1000000")),
      ("k", BigDecimal("1000")),
      ("", BigDecimal("1")),
      ("m", BigDecimal("0.001")),
      ("u", BigDecimal("0.000001")),
      ("n", BigDecimal("0.000000001")),
      ("p", BigDecimal("0.000000000001")),
      ("f", BigDecimal("0.000000000000001")),
      ("a", BigDecimal("0.000000000000000001")),
      ("z", BigDecimal("0.000000000000000000001")),
      ("y", BigDecimal("0.000000000000000000000001"))
    ).collectFirst {
      case (prefix, multiplier: BigDecimal) if d >= multiplier =>
        (prefix, multiplier)
    } match {
      case Some((prefix: String, multiplier: BigDecimal)) =>
        (d / multiplier)
          .setScale(decimalDigits, BigDecimal.RoundingMode.HALF_UP) match {
          case v if v.isWhole() =>
            v.toInt.toString() + (if (prefix != "") prefix else unit)
          case v => // "thankfully" BigDecimal.toString is not locale aware...
            v.toString()
              .replace(".", if (prefix != "") prefix else unit)
              .replaceAll("0*$", "")
        }
      case _ =>
        throw new NumberFormatException(f"No valid SI-prefix available for $d")
    }
  }
}
